name: Planetoid

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_client_linux:
    name: Build clients Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build for target x86_64-unknown-linux-gnu
      run: cargo build --release

    - name: Run clippy for target x86_64-unknown-linux-gnu
      run: cargo clippy --release >clippy.output 2>&1 ; cat clippy.output ;! egrep -q "warning|error:" clippy.output

    - name: Run tests
      run: cargo test --release

    - name: Prepare produced files
      run: |
        mkdir -p gitlab-push-and-mr-linux-x86_64
        cp client/target/debug/gitlab-push-and-mr gitlab-push-and-mr-linux-x86_64
        tar zcvvf gitlab-push-and-mr-linux-x86_64.tar.gz gitlab-push-and-mr-linux-x86_64

    - name: 'Upload planetoid-linux-x86_64.tar.gz'
      uses: actions/upload-artifact@v2
      with:
        name: gitlab-push-and-mr-linux-x86_64.tar.gz
        path: gitlab-push-and-mr-linux-x86_64.tar.gz
        retention-days: 1

  build_client_windows:
    name: Build client windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build for target x86_64-pc-windows-msvc
      run: cargo build --release

    - name: Run tests
      run: cargo test --release

    - name: Prepare produced files
      run: |
        new-item -Name gitlab-push-and-mr-windows -ItemType directory
        Copy-Item -Path "client\target\debug\gitlab-push-and-mr.exe" -Destination "gitlab-push-and-mr-windows"
        Copy-Item -Path "client\sounds" -Destination "gitlab-push-and-mr-windows" -Recurse
        Compress-Archive -Path gitlab-push-and-mr-windows -DestinationPath gitlab-push-and-mr-windows.zip

    - name: 'Upload planetoid-windows.zip'
      uses: actions/upload-artifact@v2
      with:
        name: gitlab-push-and-mr-windows.zip
        path: gitlab-push-and-mr-windows.zip
        retention-days: 1

  create_github_release:
    name: Create Github release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build_client_linux,build_client_windows]

    steps:
    - uses: actions/checkout@v2

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2

    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Create a Github release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: Planetoid
        files: |
          gitlab-push-and-mr-windows.zip
          gitlab-push-and-mr-linux-x86_64.tar.gz
